source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5.1'
gem 'sqlite3'
gem 'grape'
gem 'grape-entity'

group :development do
  gem "awesome_print", require:"ap"
  gem 'better_errors'
  gem 'spring-commands-rspec'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'dotenv-rails'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :test do
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'simplecov'
  gem 'shoulda-matchers', require: false
end

